# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

        config.vm.box = "ubuntu/xenial64"

        # I can use provision to show text on screen this way
        config.vm.provision "shell", inline: "echo this is a multi VM setup"

        config.vm.define "node01" do |node01|
                node01.vm.network "private_network", bridge: "vboxnet0: hostonly", ip: "192.0.2.1"
        end

        config.vm.define "node02" do |node02|
                node02.vm.network "private_network", bridge: "vboxnet0: hostonly", ip: "192.0.2.2"
        end

end

